image: node:latest

services:
  - postgres:latest

variables:
  POSTGRES_DB: my_products_tests
  POSTGRES_USER: codex-coder
  POSTGRES_PASSWORD: "pg123"
  
cache: 
  path: 
    - node_modules/

postgresql:
  script:
    - npm test