stages: 
  - build
  - test

image: node:latest

services:
  - postgres:latest


build:
  stage: build
  script: 
    - npm install

test:
  stage: test
  script: 
    - npm test

  
postgresql:
  script:
    - npm test