language: node_js

env:
     - DB=postgresql://postgres@localhost:5432/my_products

     node_js:  
        - "8.9.4"

before_script:
  - psql -c 'create database  my_products;' -U postgres
  - psql -U postgres -d my_products -a -f tables.sql

addons:
    apt:
    packages:
    - postgresql-server-dev-9.2